// Module keys for browser APIs
export const moduleKeys = [
  'app',
  'autoUpdater',
  'BaseWindow',
  'BrowserView',
  'BrowserWindow',
  'clipboard',
  'contentTracing',
  'crashReporter',
  'desktopCapturer',
  'dialog',
  'globalShortcut',
  'ipcMain',
  'ImageView',
  'inAppPurchase',
  'Menu',
  'MenuItem',
  'MessageChannelMain',
  'nativeTheme',
  'net',
  'netLog',
  'Notification',
  'powerMonitor',
  'powerSaveBlocker',
  'pushNotifications',
  'protocol',
  'safeStorage',
  'screen',
  'ServiceWorkerMain',
  'session',
  'ShareMenu',
  'systemPreferences',
  'TouchBar',
  'Tray',
  'utilityProcess',
  'View',
  'webContents',
  'WebContentsView',
  'webFrameMain'
] as const;

export type ModuleKey = typeof moduleKeys[number];