# Keep GitHub Actions up to date with GitHub's Dependabot...
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - "no-backport"
      - "semver/none"
    target-branch: main
  - package-ecosystem: npm
    directories:
      - /
      - /spec
      - /npm
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    labels:
      - "no-backport"
    open-pull-requests-limit: 0
  - package-ecosystem: npm
    directories:
      - /
      - /spec
      - /npm
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    labels:
      - "backport-check-skip"
    open-pull-requests-limit: 0
    target-branch: 45-x-y
  - package-ecosystem: npm
    directories:
      - /
      - /spec
      - /npm
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    labels:
      - "backport-check-skip"
    open-pull-requests-limit: 0
    target-branch: 44-x-y
  - package-ecosystem: npm
    directories:
      - /
      - /spec
      - /npm
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    labels:
      - "backport-check-skip"
    open-pull-requests-limit: 0
    target-branch: 43-x-y
  - package-ecosystem: npm
    directories:
      - /
      - /spec
      - /npm
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    labels:
      - "backport-check-skip"
    open-pull-requests-limit: 0
    target-branch: 42-x-y
