enableScripts: false

nmHoistingLimits: workspaces

packageExtensions:
  abstract-socket@*:
    dependencies:
      node-addon-api: 8.0.0

nodeLinker: node-modules

npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - "@electron/*"

httpProxy: "${HTTP_PROXY:-}"

httpsProxy: "${HTTPS_PROXY:-}"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
