enableScripts: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - "@electron/*"

httpProxy: "${HTTP_PROXY:-}"

httpsProxy: "${HTTPS_PROXY:-}"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
