// Copyright (c) 2014 GitHub, Inc.
// Use of this source code is governed by the MIT license that can be
// found in the LICENSE file.

// This file is generated by script/bootstrap.py, you should never modify it
// by hand.

#ifndef ATOM_COMMON_CHROME_VERSION_H_
#define ATOM_COMMON_CHROME_VERSION_H_

#define CHROME_VERSION_STRING "51.0.2704.79"
#define CHROME_VERSION "v" CHROME_VERSION_STRING

#endif  // ATOM_COMMON_CHROME_VERSION_H_
