// Copyright (c) 2014 GitHub, Inc.
// Use of this source code is governed by the MIT license that can be
// found in the LICENSE file.

// This file is generated by script/bootstrap.py, you should never modify it
// by hand.

#pragma once

#define CHROME_VERSION_STRING "52.0.2743.82"
#define CHROME_VERSION "v" CHROME_VERSION_STRING
