binding = process.atomBinding 'clipboard'
module.exports =
  availableFormats: (type='standard') -> binding._availableFormats type
  read: (format, type='standard') -> binding._read format, type
  readText: (type='standard') -> binding._readText type
  writeText: (text, type='standard') -> binding._writeText text, type
  readHtml: (type='standard') -> binding._readHtml type
  writeHtml: (markup, type='standard') -> binding._writeHtml markup, type
  readImage: (type='standard') -> binding._readImage type
  writeImage: (image, type='standard') -> binding._writeImage image, type
  clear: (type='standard') -> binding._clear type
