#!/usr/bin/env bash

set -ex

script/cpplint

# Make cloned repository complete
git fetch --unshallow origin HEAD

# Clone Electron
git clone https://github.com/electron/electron --depth 1 --recursive

# Checkout current brightray commit into Electron
cd electron/vendor/brightray
git fetch ../../..
git reset --hard FETCH_HEAD

# Commit change
cd ../..
git add vendor/brightray
git config --local user.email "test@github.com"
git config --local user.name "Test"
git commit --message 'Upgrading brightray'

# Bootstrap Electron
npm run bootstrap -- --dev

# Build Electron with brightray commit
npm run build
