// Copyright (c) 2014 GitHub, Inc.
// Use of this source code is governed by the MIT license that can be
// found in the LICENSE file.

// This file is generated by script/bootstrap.py, you should never modify it
// by hand.

#ifndef ELECTRON_COMMON_CHROME_VERSION_H_
#define ELECTRON_COMMON_CHROME_VERSION_H_

#define CHROME_VERSION_STRING "49.0.2623.75"
#define CHROME_VERSION "v" CHROME_VERSION_STRING

#endif  // ELECTRON_COMMON_CHROME_VERSION_H_
