name: 'Set Chromium Git Helper'
description: 'Sets Chromium Git Helper to allow for a higher request limit'
runs:
  using: "composite"
  steps:
  - name: Save the chromium git credentials to a file
    shell: bash
    run: |
      if [[ -z "${{ env.CHROMIUM_GIT_AUTH }}" ]]; then
        echo "CHROMIUM_GIT_AUTH is not set - cannot authenticate."
        exit 0
      fi
      if [[ "${{ runner.os }}" != "Windows" ]]; then
        cd $HOME
      fi
      echo "${{ env.CHROMIUM_GIT_AUTH }}" > .chromium_git_auth
  
  - name: Set the chromium git helper to use auth from a file
    shell: bash
    run: |
      if [[ "${{ runner.os }}" == "Windows" ]]; then
        if [[ ! -f "/c/actions-runner/_work/electron/electron/.chromium_git_auth" ]]; then
          echo "File /c/actions-runner/_work/electron/electron/.chromium_git_auth does not exist - cannot authenticate."
          exit 0
        fi
      else
        if [[ ! -f "$HOME/.chromium_git_auth" ]]; then
          echo "File $HOME/.chromium_git_auth does not exist - cannot authenticate."
          exit 0
        fi
      fi
      if [[ -z "${{ env.CHROMIUM_GIT_USER }}" ]]; then
        echo "CHROMIUM_GIT_USER is not set - cannot authenticate."
        exit 0
      fi
      git config --global credential.https://chromium.googlesource.com.username "${{ env.CHROMIUM_GIT_USER }}"
      if [[ "${{ runner.os }}" == "Windows" ]]; then
        git config --global credential.https://chromium.googlesource.com.helper '!f() { test "$1" = get && echo "password=$(cat /c/actions-runner/_work/electron/electron/.chromium_git_auth)"; }; f'
      else
        git config --global credential.https://chromium.googlesource.com.helper '!f() { test "$1" = get && echo "password=$(cat $HOME/.chromium_git_auth)"; }; f'
      fi
