name: 'Install Build Tools'
description: 'Installs an exact SHA of build tools'
runs:
  using: "composite"
  steps:
  - name: Install Build Tools
    shell: bash
    run: |
      if [ "$(expr substr $(uname -s) 1 10)" == "MSYS_NT-10" ]; then
        git config --global core.filemode false
        git config --global core.autocrlf false
        git config --global branch.autosetuprebase always
      fi
      export BUILD_TOOLS_SHA=33dc5186556bfbf7b0121a00cdd89ed3802e47da
      npm i -g @electron/build-tools
      e auto-update disable
