name: 'Install Build Tools'
description: 'Installs an exact SHA of build tools'
runs:
  using: "composite"
  steps:
  - name: Install Build Tools
    shell: bash
    run: |
      if [ "$(expr substr $(uname -s) 1 10)" == "MSYS_NT-10" ]; then
        git config --global core.filemode false
        git config --global core.autocrlf false
        git config --global branch.autosetuprebase always
      fi
      export BUILD_TOOLS_SHA=c3e81edd054e26ec95167b6d87fe5add11dc79e6
      npm i -g @electron/build-tools
      e auto-update disable
      if [ "$(expr substr $(uname -s) 1 10)" == "MSYS_NT-10" ]; then
        e d cipd.bat --version
        cp "C:\Python37\python.exe" "C:\Python37\python3.exe"
      fi
