name: 'Install Build Tools'
description: 'Installs an exact SHA of build tools'
runs:
  using: "composite"
  steps:
  - name: Install Build Tools
    shell: bash
    run: |
      if [ "$(expr substr $(uname -s) 1 10)" == "MSYS_NT-10" ]; then
        git config --global core.filemode false
        git config --global core.autocrlf false
        git config --global branch.autosetuprebase always
        git config --global core.fscache true
        git config --global core.preloadindex true
      fi
      export BUILD_TOOLS_SHA=6e8526315ea3b4828882497e532b8340e64e053c
      npm i -g @electron/build-tools
      e d update_depot_tools
      e auto-update disable
      e d auto-update disable
      if [ "$(expr substr $(uname -s) 1 10)" == "MSYS_NT-10" ]; then
        e d cipd.bat --version
        cp "C:\Python311\python.exe" "C:\Python311\python3.exe"
      fi
      echo "$HOME/.electron_build_tools/third_party/depot_tools" >> $GITHUB_PATH
