#!/usr/bin/env bash

# Get all changes that are not in omitted folders
changes=( `git diff --name-only --cached ':!docs' ':!script' ':!tools'` )

if [[ ${#changes[@]} -gt 0 ]]; then
	exit
fi

# Prefix the commit message with "[skip ci]"
sed -i.bak -e "1s/^/[skip ci] /" "$GIT_DIR/COMMIT_EDITMSG"