#!/usr/bin/env bash

# Load in every file that will be changed via this commit into an array
changes=( `git diff --name-only --cached` )
commit_file="../.git/COMMIT_EDITMSG"

# Load the dir patterns to skip into an array
declare -a blacklist=("script/*" "tools/*" "docs/*")

for i in "${blacklist[@]}"
do
	# Remove the current pattern from the list of changes
	changes=( ${changes[@]/$i/} )

	if [[ ${#changes[@]} -eq 0 ]]; then
		break
	fi
done

if [[ ${#changes[@]} -gt 0 ]]; then
	exit
fi

# Prefix the commit message with "[skip ci]"
sed -i.bak -e "1s/^/[skip ci] /" "$GIT_DIR/COMMIT_EDITMSG"