#!/usr/bin/env python

import os
import subprocess
import sys

from lib.util import rm_rf


SOURCE_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))


def main():
  rm_rf(os.path.join(SOURCE_ROOT, 'out'))
  rm_rf(os.path.join(SOURCE_ROOT, 'node_modules'))
  rm_rf(os.path.join(SOURCE_ROOT, 'vendor', 'brightray', 'vendor', 'download',
                     'libchromiumcontent'))

  run_script('bootstrap.py')
  run_script('cpplint.py')
  run_script('pylint.py')
  run_script('coffeelint.py')
  run_script('build.py')
  run_script('test.py', ['--ci'])
  run_script('create-dist.py')


def run_script(script, args=[]):
  script = os.path.join(SOURCE_ROOT, 'script', script)
  subprocess.check_call([sys.executable, script] + args)


if __name__ == '__main__':
  sys.exit(main())
