#!/usr/bin/env bash

MESSAGE="$(git log --format=%B -n 1 HEAD)"
case ${MESSAGE} in
  Bump* ) export ELECTRON_RELEASE=1 ;;
esac

if [[ -z "${ELECTRON_RELEASE}" ]]; then
  echo "Generating Linux $TARGET_ARCH debug build"
else
  echo "Generating Linux $TARGET_ARCH release build"
fi

set +x
set -e
set -o pipefail

git submodule sync --recursive
git submodule update --init --recursive

docker build \
  --force-rm \
  --tag electron-linux \
  .

docker run \
  --rm \
  --env TARGET_ARCH="$TARGET_ARCH" \
  --env ELECTRON_RELEASE="$ELECTRON_RELEASE" \
  --env ELECTRON_GITHUB_TOKEN="$BUILD_ELECTRON_ELECTRON_GITHUB_TOKEN" \
  --env ELECTRON_S3_BUCKET="$BUILD_ELECTRON_ELECTRON_S3_BUCKET" \
  --env ELECTRON_S3_ACCESS_KEY="$BUILD_ELECTRON_ELECTRON_S3_ACCESS_KEY" \
  --env ELECTRON_S3_SECRET_KEY="$BUILD_ELECTRON_ELECTRON_S3_SECRET_KEY" \
  --user "$UID" \
  --volume "$PWD":/workspace/electron \
  --workdir /workspace/electron \
  electron-linux script/cibuild
