#!/usr/bin/env python3
"""Writes <out>/clang_tidy.ninja: one clang-tidy step per Electron translation
unit, shaped like a compile so siso can include-scan it, cache it in the RBE
action cache and run misses remotely.

  gn gen out/X --add-export-compile-commands='//electron:*'
  script/gen-clang-tidy-ninja.py out/X
  siso ninja -C out/X -f clang_tidy.ninja electron_clang_tidy
"""

import argparse
import json
import os
import shlex
import sys

ELECTRON_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Kept in sync with script/run-clang-tidy.ts.
EXCLUDED_SUFFIXES = (
    # Build-only host tool compiled in v8_snapshot_toolchain; its generated
    # buildflag headers aren't present for clang-tidy in CI.
    '/electron_natives_codecache_main.cc',
)
EXCLUDED_SUFFIXES_CI = (
    # TODO(dsanders11): clang-tidy compilation errors in CI that don't appear
    # locally.
    '/electron_smooth_round_rect.cc',
)

DROP_FLAGS = {'-c', '-MMD', '-MD'}
DROP_FLAGS_WITH_VALUE = {'-o', '-MF', '-MT', '-MQ'}


def tidy_flags(tokens, source):
  """Compile flags minus the compiler, source, output and depfile bits."""
  flags = []
  it = iter(tokens[1:])
  for tok in it:
    if tok == source or tok in DROP_FLAGS:
      continue
    if tok in DROP_FLAGS_WITH_VALUE:
      next(it, None)
      continue
    if any(tok.startswith(f) and len(tok) > len(f) for f in DROP_FLAGS_WITH_VALUE):
      continue
    flags.append(tok)
  return flags


def ninja_escape(s):
  return s.replace('$', '$$')


def main():
  parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
  parser.add_argument('out_dir')
  parser.add_argument('--electron-dir', default=ELECTRON_DIR, help='electron checkout whose shell/ sources to check (default: this one)')
  parser.add_argument('--wrapper', help='path to run-clang-tidy-action.sh relative to out_dir (default: <electron-dir>/build/...)')
  args = parser.parse_args()

  out_dir = os.path.abspath(args.out_dir)
  electron_dir = os.path.abspath(args.electron_dir)
  electron_rel = os.path.relpath(electron_dir, out_dir)

  db_path = os.path.join(out_dir, 'compile_commands.json')
  if not os.path.exists(db_path):
    sys.exit(f'{db_path} not found; run gn gen with --add-export-compile-commands=//electron:*')
  with open(db_path, encoding='utf-8') as f:
    db = json.load(f)

  excluded = EXCLUDED_SUFFIXES + (EXCLUDED_SUFFIXES_CI if os.environ.get('CI') else ())
  shell_dir = os.path.join(electron_dir, 'shell') + os.sep
  edges = []
  seen = set()
  for entry in db:
    path = os.path.normpath(os.path.join(entry['directory'], entry['file']))
    if not path.startswith(shell_dir) or not path.endswith(('.cc', '.mm')):
      continue
    if path.endswith(excluded) or path in seen:
      continue
    seen.add(path)
    tokens = shlex.split(entry['command'])
    src = os.path.relpath(path, out_dir)
    out = 'obj/electron/clang_tidy/' + os.path.relpath(path, electron_dir) + '.tidy'
    edges.append((src, out, tokens[0], tidy_flags(tokens, entry['file'])))

  if not edges:
    sys.exit('no electron/shell translation units found in compile_commands.json')

  edges.sort()
  wrapper = args.wrapper or f'{electron_rel}/build/run-clang-tidy-action.sh'
  lines = [
      '# Generated by electron/script/gen-clang-tidy-ninja.py',
      'rule clang_tidy',
      f'  command = {wrapper} $compiler $flags -c $in -o $out',
      '  description = CLANG-TIDY $in',
      '  depfile = $out.d',
      '  deps = gcc',
      '',
  ]
  for src, out, compiler, flags in edges:
    lines.append(f'build {out}: clang_tidy {src}')
    lines.append(f'  compiler = {ninja_escape(compiler)}')
    lines.append('  flags = ' + ninja_escape(' '.join(shlex.quote(f) for f in flags)))
  lines += [
      '',
      'build electron_clang_tidy: phony ' + ' $\n    '.join(out for _, out, _, _ in edges),
      'default electron_clang_tidy',
      '',
  ]
  with open(os.path.join(out_dir, 'clang_tidy.ninja'), 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
  print(f'Wrote {len(edges)} clang-tidy steps to {os.path.join(args.out_dir, "clang_tidy.ninja")}')


if __name__ == '__main__':
  main()
