#!/usr/bin/env python3
"""Generate <out_dir>/clang_tidy.ninja: one clang-tidy build step per Electron
translation unit.

Each step's command line is an ordinary compile command with
build/run-clang-tidy-action.sh in front of it. That shape is what lets siso
scan the step's #includes, look it up in the RBE action cache and run it
remotely (see the electron/clang-tidy rule in build/siso/main.star).

Usage:
  gn gen out/X --add-export-compile-commands='//electron:*'
  script/gen-clang-tidy-ninja.py out/X
  e build -f clang_tidy.ninja --target electron_clang_tidy
"""

import collections
import json
import os
import shlex
import sys

ELECTRON_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHELL_DIR = os.path.join(ELECTRON_DIR, 'shell')

# Keep in sync with script/run-clang-tidy.ts.
SKIPPED_SOURCES = {
    # Host tool built in v8_snapshot_toolchain; its generated buildflag headers
    # don't exist in the default toolchain's gen dir.
    'shell/common/electron_natives_codecache_main.cc',
}
if os.environ.get('CI'):
  # TODO(dsanders11): clang-tidy compilation errors in CI that don't reproduce
  # locally.
  SKIPPED_SOURCES.add('shell/renderer/electron_smooth_round_rect.cc')

Step = collections.namedtuple('Step', ['source', 'output', 'compiler', 'flags'])


def compile_flags(command, source):
  """Splits a compile command into (compiler, flags), dropping the source file
  and the output/depfile arguments since the wrapper supplies its own."""
  compiler, *args = shlex.split(command)
  flags = []
  skip_next = False
  for arg in args:
    if skip_next:
      skip_next = False
    elif arg in ('-o', '-MF'):
      skip_next = True
    elif arg not in ('-c', '-MMD', source):
      flags.append(arg)
  return compiler, flags


def tidy_steps(out_dir):
  with open(os.path.join(out_dir, 'compile_commands.json'), encoding='utf-8') as f:
    compile_commands = json.load(f)

  steps = {}
  for entry in compile_commands:
    path = os.path.normpath(os.path.join(entry['directory'], entry['file']))
    electron_path = os.path.relpath(path, ELECTRON_DIR)
    if not path.startswith(SHELL_DIR + os.sep) or not path.endswith(('.cc', '.mm')):
      continue
    if electron_path in SKIPPED_SOURCES or path in steps:
      continue
    compiler, flags = compile_flags(entry['command'], entry['file'])
    steps[path] = Step(
        source=os.path.relpath(path, out_dir),
        output=f'obj/electron/clang_tidy/{electron_path}.tidy',
        compiler=compiler,
        flags=flags,
    )
  return sorted(steps.values())


def ninja_escape(text):
  return text.replace('$', '$$')


def write_ninja(out_dir, steps):
  wrapper = os.path.join(os.path.relpath(ELECTRON_DIR, out_dir), 'build', 'run-clang-tidy-action.sh')
  with open(os.path.join(out_dir, 'clang_tidy.ninja'), 'w', encoding='utf-8') as ninja:
    ninja.write(f'''# Generated by electron/script/gen-clang-tidy-ninja.py

rule clang_tidy
  command = {wrapper} $compiler $flags -c $in -o $out
  description = CLANG-TIDY $in
  depfile = $out.d
  deps = gcc

''')
    for step in steps:
      flags = ' '.join(shlex.quote(flag) for flag in step.flags)
      ninja.write(f'build {step.output}: clang_tidy {step.source}\n')
      ninja.write(f'  compiler = {ninja_escape(step.compiler)}\n')
      ninja.write(f'  flags = {ninja_escape(flags)}\n')

    outputs = ' $\n    '.join(step.output for step in steps)
    ninja.write(f'\nbuild electron_clang_tidy: phony {outputs}\n')
    ninja.write('default electron_clang_tidy\n')


def main():
  if len(sys.argv) != 2:
    sys.exit(__doc__)
  out_dir = os.path.abspath(sys.argv[1])
  if not os.path.exists(os.path.join(out_dir, 'compile_commands.json')):
    sys.exit(f"No compile_commands.json in {out_dir}; run gn gen with --add-export-compile-commands='//electron:*'")

  steps = tidy_steps(out_dir)
  if not steps:
    sys.exit('No electron/shell translation units in compile_commands.json')
  write_ninja(out_dir, steps)
  print(f'Wrote {len(steps)} clang-tidy steps to {os.path.join(sys.argv[1], "clang_tidy.ninja")}')


if __name__ == '__main__':
  main()
