#!/usr/bin/env python3
"""Generate <out_dir>/clang_tidy.ninja: one clang-tidy build step per Electron
translation unit.

Each step's command line is an ordinary compile command with
build/run-clang-tidy-action.sh in front of it. That shape is what lets siso
scan the step's #includes, look it up in the RBE action cache and run it
remotely (see the electron/clang-tidy rule in build-tools' tools/main.star).

This is CI plumbing, run by the clang-tidy job. To run clang-tidy locally use
`yarn lint:clang-tidy`. If you do run this yourself, the out dir must already
be built (the steps need its generated headers), and it has to run through
`e d` so that gn is on PATH:

  e d python3 script/gen-clang-tidy-ninja.py ../out/X
  e build -f clang_tidy.ninja --target electron_clang_tidy
"""

import collections
import json
import os
import shlex
import shutil
import subprocess
import sys

ELECTRON_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.dirname(ELECTRON_DIR)
SHELL_DIR = os.path.join(ELECTRON_DIR, 'shell')

# Keep in sync with script/run-clang-tidy.ts.
SKIPPED_SOURCES = {
    # Host tool built in v8_snapshot_toolchain; its generated buildflag headers
    # don't exist in the default toolchain's gen dir.
    'shell/common/electron_natives_codecache_main.cc',
}
if os.environ.get('CI'):
  # TODO(dsanders11): clang-tidy compilation errors in CI that don't reproduce
  # locally.
  SKIPPED_SOURCES.add('shell/renderer/electron_smooth_round_rect.cc')

Step = collections.namedtuple('Step', ['source', 'output', 'compiler', 'flags'])


def parse_compile_command(command, source):
  """Splits a clang++ or clang-cl compile command into (compiler, object, flags).
  flags omits the source file and the output/depfile/pdb arguments, since the
  wrapper supplies its own."""
  compiler, *args = shlex.split(command)
  flags = []
  obj = None
  args = iter(args)
  for arg in args:
    if arg == '-o':
      obj = next(args)
    elif arg.startswith('/Fo'):
      obj = arg[len('/Fo'):]
    elif arg == '-MF':
      next(args)
    elif arg in ('-c', '/c', '-MMD', source) or arg.startswith(('/Fd', '/showIncludes')):
      pass
    else:
      flags.append(arg)
  return compiler, obj, flags


def tidy_steps(out_dir):
  with open(os.path.join(out_dir, 'compile_commands.json'), encoding='utf-8') as f:
    compile_commands = json.load(f)

  # A file built by several targets (with different flags) gets a step per
  # target, told apart by object path like the compiles themselves.
  steps = []
  for entry in compile_commands:
    path = os.path.normpath(os.path.join(entry['directory'], entry['file']))
    if not path.startswith(SHELL_DIR + os.sep) or not path.endswith(('.cc', '.mm')):
      continue
    if os.path.relpath(path, ELECTRON_DIR) in SKIPPED_SOURCES:
      continue
    compiler, obj, flags = parse_compile_command(entry['command'], entry['file'])
    steps.append(Step(
        source=os.path.relpath(path, out_dir),
        output=f'{obj}.tidy',
        compiler=compiler,
        flags=tuple(flags),
    ))
  return sorted(set(steps), key=lambda step: step.output)


def ninja_escape(text):
  return text.replace('$', '$$')


def write_ninja(out_dir, steps):
  wrapper = os.path.join(os.path.relpath(ELECTRON_DIR, out_dir), 'build', 'run-clang-tidy-action.sh')
  # How ninja/siso learn each step's header dependencies. This also tells siso
  # which flag style to expect when it scans the command for #includes.
  if os.path.basename(steps[0].compiler).startswith('clang-cl'):
    deps = 'deps = msvc'
  else:
    deps = 'depfile = $out.d\n  deps = gcc'

  with open(os.path.join(out_dir, 'clang_tidy.ninja'), 'w', encoding='utf-8') as ninja:
    ninja.write(f'''# Generated by electron/script/gen-clang-tidy-ninja.py

rule clang_tidy
  command = {wrapper} $compiler $flags -c $in -o $out
  description = CLANG-TIDY $in
  {deps}

''')
    for step in steps:
      flags = ' '.join(shlex.quote(flag) for flag in step.flags)
      ninja.write(f'build {step.output}: clang_tidy {step.source}\n')
      ninja.write(f'  compiler = {ninja_escape(step.compiler)}\n')
      ninja.write(f'  flags = {ninja_escape(flags)}\n')

    outputs = ' $\n    '.join(step.output for step in steps)
    ninja.write(f'\nbuild electron_clang_tidy: phony {outputs}\n')
    ninja.write('default electron_clang_tidy\n')


def main():
  if len(sys.argv) != 2:
    sys.exit(__doc__)
  out_dir = os.path.abspath(sys.argv[1])

  # Regenerate compile_commands.json here rather than trusting an old one, so
  # the steps always carry the out dir's current flags.
  gn = shutil.which('gn')
  if not gn:
    sys.exit('gn is not on PATH; run this through `e d`')
  subprocess.check_call([gn, 'gen', out_dir, '--add-export-compile-commands=//electron:*'], cwd=SRC_DIR)

  steps = tidy_steps(out_dir)
  if not steps:
    sys.exit('No electron/shell translation units in compile_commands.json')
  write_ninja(out_dir, steps)
  print(f'Wrote {len(steps)} clang-tidy steps to {os.path.join(sys.argv[1], "clang_tidy.ninja")}')


if __name__ == '__main__':
  main()
