#!/bin/bash

cd "$(dirname $0)/.."

. script/lib/polite-curl

[ -d frameworks ] || mkdir frameworks
cd frameworks

FRAMEWORKS_URL='https://gh-contractor-zcbenz.s3.amazonaws.com/frameworks'

trap 'rm -f *.zip' EXIT

function download_and_unzip() {
  if ! [ -d $1.framework ]; then
    echo "Downloading $1..."
    polite_curl "$FRAMEWORKS_URL/$1.framework.zip" > $1.framework.zip
    unzip $1.framework.zip
  fi
}

download_and_unzip Quincy
download_and_unzip Sparkle
