#!/usr/bin/env bash

set -ex

# Make cloned repository complete
git fetch --unshallow origin HEAD

# Clone Electron
git clone https://github.com/electron/electron --depth 1 --recursive

# Checkout current native_mate commit into Electron
cd electron/vendor/native_mate
git fetch ../../..
git reset --hard FETCH_HEAD

# Commit change
cd ../..
git add vendor/native_mate
git config --local user.email "test@github.com"
git config --local user.name "Test"
git commit --message 'Upgrading native_mate'

# Bootstrap Electron
npm run bootstrap -- --dev

# Build Electron with native_mate commit
npm run build
