name: windows-io-repro

on:
  push:
    branches:
      - sam/windows-io-repro

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/pipeline-segment-electron-build.yml
    with:
      build-runs-on: electron-arc-centralus-windows-amd64-32core
      target-platform: win
      target-arch: x64
      is-release: false
      gn-build-type: testing
      generate-symbols: false
      upload-to-storage: '0'
    secrets: inherit
